### ISSUE TITLE
[BUG] pg_restore --clean with github actions not working

### ISSUE THREAD

**Issue by nadiaamirat** [tj-actions/pg-restore#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

`Warning: Unexpected input(s) 'options', valid inputs are ['database_url', 'backup_file']`

### To Reproduce

GitHub actions workflow
```yml
    steps:
      - uses: actions/checkout@v2
      - name: Postgres Backup Restore
        uses: tj-actions/pg-restore@v4.5
        with:
          database_url: "postgres://test_user:test_password@localhost:5432/test_db"
          backup_file: "backups/backup.sql"
          options: "-c"
```

### What OS are you seeing the problem on?

ubuntu-18.04

### Expected behavior?

clean content of database if exist before restore back up

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
